# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20170616_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('remark', models.TextField()),
            ],
        ),
    ]
