# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
    ]
