# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_auto_20170619_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
