# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_auto_20170619_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEventSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.SmallIntegerField(default=0)),
                ('reps', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='posteventset',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Event'),
        ),
        migrations.AddField(
            model_name='posteventset',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Post'),
        ),
    ]
