# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_auto_20170619_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='workout_date',
        ),
    ]
