# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20170619_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_1', models.SmallIntegerField(null=True)),
                ('set_2', models.SmallIntegerField(null=True)),
                ('set_3', models.SmallIntegerField(null=True)),
                ('set_4', models.SmallIntegerField(null=True)),
                ('set_5', models.SmallIntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='posteventset',
            name='event',
        ),
        migrations.RemoveField(
            model_name='posteventset',
            name='post',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='PostEventSet',
        ),
        migrations.AddField(
            model_name='postevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Event'),
        ),
        migrations.AddField(
            model_name='postevent',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Post'),
        ),
    ]
