# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20170620_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postevent',
            old_name='set_1',
            new_name='set1',
        ),
        migrations.RenameField(
            model_name='postevent',
            old_name='set_2',
            new_name='set2',
        ),
        migrations.RenameField(
            model_name='postevent',
            old_name='set_3',
            new_name='set3',
        ),
        migrations.RenameField(
            model_name='postevent',
            old_name='set_4',
            new_name='set4',
        ),
        migrations.RenameField(
            model_name='postevent',
            old_name='set_5',
            new_name='set5',
        ),
    ]
