# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20170620_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='events',
            field=models.ManyToManyField(through='journal.PostEvent', to='journal.Event'),
        ),
        migrations.AddField(
            model_name='postevent',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='set1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='set2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='set3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='set4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postevent',
            name='set5',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
