# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_auto_20170620_1309'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostEvent',
            new_name='Performance',
        ),
        migrations.RemoveField(
            model_name='post',
            name='events',
        ),
        migrations.AddField(
            model_name='post',
            name='performances',
            field=models.ManyToManyField(through='journal.Performance', to='journal.Event'),
        ),
    ]
