# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_auto_20170620_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': '종목', 'verbose_name_plural': '종목'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': '수행내역', 'verbose_name_plural': '수행내역'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='performances',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='종목명'),
        ),
        migrations.AlterField(
            model_name='event',
            name='remark',
            field=models.TextField(blank=True, verbose_name='기타'),
        ),
        migrations.AlterField(
            model_name='event',
            name='unit',
            field=models.CharField(default='Kg', max_length=10, verbose_name='단위'),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='값'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Event', verbose_name='종목'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='journal.Post'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='set1',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='세트1'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='set2',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='세트2'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='set3',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='세트3'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='set4',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='세트4'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='set5',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='세트5'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='값'),
        ),
        migrations.AlterField(
            model_name='post',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='비고'),
        ),
        migrations.AlterField(
            model_name='post',
            name='workout_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='활동일시'),
        ),
    ]
